name: Deploy to AlwaysData via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}" >> laravel-backend/.env
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> laravel-backend/.env
          echo "SENDER_NAME=${{ secrets.SENDER_NAME }}" >> laravel-backend/.env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> laravel-backend/.env
          echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> laravel-backend/.env
          echo "FIREBASE_PRIVATE_KEY=\"${{ secrets.FIREBASE_PRIVATE_KEY }}\"" >> laravel-backend/.env
          echo "DB_HOST=${{ secrets.ALWAYSDATA_DB_HOST }}" >> laravel-backend/.env
          echo "DB_USER=${{ secrets.ALWAYSDATA_DB_USER }}" >> laravel-backend/.env
          echo "DB_PASS=${{ secrets.ALWAYSDATA_DB_PASS }}" >> laravel-backend/.env
          echo "DB_NAME=${{ secrets.ALWAYSDATA_DB_NAME }}" >> laravel-backend/.env

      - name: Upload via FTP to AlwaysData
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ALWAYSDATA_FTP_SERVER }}
          username: ${{ secrets.ALWAYSDATA_FTP_USERNAME }}
          password: ${{ secrets.ALWAYSDATA_FTP_PASSWORD }}
          port: 990
          protocol: ftps
          local-dir: ./laravel-backend/
          server-dir: ./www/
