# name: Deploy Landing Page to FTP

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Get latest code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Build landing page
#         run: |
#           cd landing-page
#           node build.js

#       - name: Prepare landing page
#         run: |
#           mkdir -p deploy
#           cp -r landing-page/* deploy/
#           rm -rf deploy/components deploy/template.html deploy/build.js deploy/package.json deploy/README.md

#       - name: Upload via FTP
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           port: 21
#           protocol: ftp
#           local-dir: ./deploy/
#           server-dir: ./byahero.app/htdocs/